# Generated by Django 5.1.1 on 2024-10-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new')),
            ],
        ),
    ]
